// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfifo_dequeue.h"

extern XFifo_dequeue_Config XFifo_dequeue_ConfigTable[];

XFifo_dequeue_Config *XFifo_dequeue_LookupConfig(u16 DeviceId) {
	XFifo_dequeue_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFIFO_DEQUEUE_NUM_INSTANCES; Index++) {
		if (XFifo_dequeue_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFifo_dequeue_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFifo_dequeue_Initialize(XFifo_dequeue *InstancePtr, u16 DeviceId) {
	XFifo_dequeue_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFifo_dequeue_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFifo_dequeue_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

