// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XFIFO_DEQUEUE_H
#define XFIFO_DEQUEUE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfifo_dequeue_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axi_fifo_BaseAddress;
} XFifo_dequeue_Config;
#endif

typedef struct {
    u32 Axi_fifo_BaseAddress;
    u32 IsReady;
} XFifo_dequeue;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFifo_dequeue_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFifo_dequeue_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFifo_dequeue_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFifo_dequeue_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFifo_dequeue_Initialize(XFifo_dequeue *InstancePtr, u16 DeviceId);
XFifo_dequeue_Config* XFifo_dequeue_LookupConfig(u16 DeviceId);
int XFifo_dequeue_CfgInitialize(XFifo_dequeue *InstancePtr, XFifo_dequeue_Config *ConfigPtr);
#else
int XFifo_dequeue_Initialize(XFifo_dequeue *InstancePtr, const char* InstanceName);
int XFifo_dequeue_Release(XFifo_dequeue *InstancePtr);
#endif

void XFifo_dequeue_Start(XFifo_dequeue *InstancePtr);
u32 XFifo_dequeue_IsDone(XFifo_dequeue *InstancePtr);
u32 XFifo_dequeue_IsIdle(XFifo_dequeue *InstancePtr);
u32 XFifo_dequeue_IsReady(XFifo_dequeue *InstancePtr);
void XFifo_dequeue_EnableAutoRestart(XFifo_dequeue *InstancePtr);
void XFifo_dequeue_DisableAutoRestart(XFifo_dequeue *InstancePtr);
u32 XFifo_dequeue_GetReturn(XFifo_dequeue *InstancePtr);


void XFifo_dequeue_InterruptGlobalEnable(XFifo_dequeue *InstancePtr);
void XFifo_dequeue_InterruptGlobalDisable(XFifo_dequeue *InstancePtr);
void XFifo_dequeue_InterruptEnable(XFifo_dequeue *InstancePtr, u32 Mask);
void XFifo_dequeue_InterruptDisable(XFifo_dequeue *InstancePtr, u32 Mask);
void XFifo_dequeue_InterruptClear(XFifo_dequeue *InstancePtr, u32 Mask);
u32 XFifo_dequeue_InterruptGetEnabled(XFifo_dequeue *InstancePtr);
u32 XFifo_dequeue_InterruptGetStatus(XFifo_dequeue *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
