// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfifo_dequeue.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFifo_dequeue_CfgInitialize(XFifo_dequeue *InstancePtr, XFifo_dequeue_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi_fifo_BaseAddress = ConfigPtr->Axi_fifo_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFifo_dequeue_Start(XFifo_dequeue *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL) & 0x80;
    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFifo_dequeue_IsDone(XFifo_dequeue *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFifo_dequeue_IsIdle(XFifo_dequeue *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFifo_dequeue_IsReady(XFifo_dequeue *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFifo_dequeue_EnableAutoRestart(XFifo_dequeue *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL, 0x80);
}

void XFifo_dequeue_DisableAutoRestart(XFifo_dequeue *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_CTRL, 0);
}

u32 XFifo_dequeue_GetReturn(XFifo_dequeue *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_AP_RETURN);
    return Data;
}
void XFifo_dequeue_InterruptGlobalEnable(XFifo_dequeue *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_GIE, 1);
}

void XFifo_dequeue_InterruptGlobalDisable(XFifo_dequeue *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_GIE, 0);
}

void XFifo_dequeue_InterruptEnable(XFifo_dequeue *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_IER);
    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_IER, Register | Mask);
}

void XFifo_dequeue_InterruptDisable(XFifo_dequeue *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_IER);
    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_IER, Register & (~Mask));
}

void XFifo_dequeue_InterruptClear(XFifo_dequeue *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFifo_dequeue_WriteReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_ISR, Mask);
}

u32 XFifo_dequeue_InterruptGetEnabled(XFifo_dequeue *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_IER);
}

u32 XFifo_dequeue_InterruptGetStatus(XFifo_dequeue *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFifo_dequeue_ReadReg(InstancePtr->Axi_fifo_BaseAddress, XFIFO_DEQUEUE_AXI_FIFO_ADDR_ISR);
}

