# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TAIGA-RIP_Zybo.xdc

# Block Designs: bd/TAIGA/TAIGA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA || ORIG_REF_NAME==TAIGA}]

# IP: bd/TAIGA/ip/TAIGA_processing_system7_0_0/TAIGA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_processing_system7_0_0 || ORIG_REF_NAME==TAIGA_processing_system7_0_0}]

# IP: bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_0 || ORIG_REF_NAME==TAIGA_axi_gpio_0_0}]

# IP: bd/TAIGA/ip/TAIGA_production_controller_axi_periph_0/TAIGA_production_controller_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_production_controller_axi_periph_0 || ORIG_REF_NAME==TAIGA_production_controller_axi_periph_0}]

# IP: bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_rst_production_controller_200M_0 || ORIG_REF_NAME==TAIGA_rst_production_controller_200M_0}]

# IP: bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_0/TAIGA_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==TAIGA_axi_fifo_mm_s_0_0}]

# IP: bd/TAIGA/ip/TAIGA_xbar_0/TAIGA_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_xbar_0 || ORIG_REF_NAME==TAIGA_xbar_0}]

# IP: bd/TAIGA/ip/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_fifo_generator_0_0 || ORIG_REF_NAME==TAIGA_fifo_generator_0_0}]

# IP: bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_fifo_production_to_IOI_0 || ORIG_REF_NAME==TAIGA_fifo_production_to_IOI_0}]

# IP: bd/TAIGA/ip/TAIGA_FIFO_multiplexer_0_0/TAIGA_FIFO_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_FIFO_multiplexer_0_0 || ORIG_REF_NAME==TAIGA_FIFO_multiplexer_0_0}]

# IP: bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_microblaze_0_0 || ORIG_REF_NAME==TAIGA_microblaze_0_0}]

# IP: bd/TAIGA/ip/TAIGA_dlmb_v10_0/TAIGA_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_dlmb_v10_0 || ORIG_REF_NAME==TAIGA_dlmb_v10_0}]

# IP: bd/TAIGA/ip/TAIGA_ilmb_v10_0/TAIGA_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_ilmb_v10_0 || ORIG_REF_NAME==TAIGA_ilmb_v10_0}]

# IP: bd/TAIGA/ip/TAIGA_dlmb_bram_if_cntlr_0/TAIGA_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TAIGA_dlmb_bram_if_cntlr_0}]

# IP: bd/TAIGA/ip/TAIGA_ilmb_bram_if_cntlr_0/TAIGA_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TAIGA_ilmb_bram_if_cntlr_0}]

# IP: bd/TAIGA/ip/TAIGA_lmb_bram_0/TAIGA_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_lmb_bram_0 || ORIG_REF_NAME==TAIGA_lmb_bram_0}]

# IP: bd/TAIGA/ip/TAIGA_backup_controller_axi_periph_0/TAIGA_backup_controller_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_backup_controller_axi_periph_0 || ORIG_REF_NAME==TAIGA_backup_controller_axi_periph_0}]

# IP: bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_backup_controller_axi_intc_0 || ORIG_REF_NAME==TAIGA_backup_controller_axi_intc_0}]

# IP: bd/TAIGA/ip/TAIGA_mdm_1_0/TAIGA_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_mdm_1_0 || ORIG_REF_NAME==TAIGA_mdm_1_0}]

# IP: bd/TAIGA/ip/TAIGA_axi_timer_0_0/TAIGA_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_timer_0_0 || ORIG_REF_NAME==TAIGA_axi_timer_0_0}]

# IP: bd/TAIGA/ip/TAIGA_xbar_1/TAIGA_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_xbar_1 || ORIG_REF_NAME==TAIGA_xbar_1}]

# IP: bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_1 || ORIG_REF_NAME==TAIGA_axi_gpio_0_1}]

# IP: bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_1/TAIGA_axi_fifo_mm_s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_fifo_mm_s_0_1 || ORIG_REF_NAME==TAIGA_axi_fifo_mm_s_0_1}]

# IP: bd/TAIGA/ip/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_fifo_IOI_to_production_0 || ORIG_REF_NAME==TAIGA_fifo_IOI_to_production_0}]

# IP: bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_fifo_production_to_IOI_1 || ORIG_REF_NAME==TAIGA_fifo_production_to_IOI_1}]

# IP: bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_microblaze_0_1 || ORIG_REF_NAME==TAIGA_microblaze_0_1}]

# IP: bd/TAIGA/ip/TAIGA_dlmb_v10_1/TAIGA_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_dlmb_v10_1 || ORIG_REF_NAME==TAIGA_dlmb_v10_1}]

# IP: bd/TAIGA/ip/TAIGA_ilmb_v10_1/TAIGA_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_ilmb_v10_1 || ORIG_REF_NAME==TAIGA_ilmb_v10_1}]

# IP: bd/TAIGA/ip/TAIGA_dlmb_bram_if_cntlr_1/TAIGA_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==TAIGA_dlmb_bram_if_cntlr_1}]

# IP: bd/TAIGA/ip/TAIGA_ilmb_bram_if_cntlr_1/TAIGA_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==TAIGA_ilmb_bram_if_cntlr_1}]

# IP: bd/TAIGA/ip/TAIGA_lmb_bram_1/TAIGA_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_lmb_bram_1 || ORIG_REF_NAME==TAIGA_lmb_bram_1}]

# IP: bd/TAIGA/ip/TAIGA_IO_intermediary_axi_periph_0/TAIGA_IO_intermediary_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_IO_intermediary_axi_periph_0 || ORIG_REF_NAME==TAIGA_IO_intermediary_axi_periph_0}]

# IP: bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_IO_intermediary_axi_intc_0 || ORIG_REF_NAME==TAIGA_IO_intermediary_axi_intc_0}]

# IP: bd/TAIGA/ip/TAIGA_IO_intermediary_xlconcat_0/TAIGA_IO_intermediary_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_IO_intermediary_xlconcat_0 || ORIG_REF_NAME==TAIGA_IO_intermediary_xlconcat_0}]

# IP: bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_axi_quad_spi_0_0}]

# IP: bd/TAIGA/ip/TAIGA_xbar_2/TAIGA_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_xbar_2 || ORIG_REF_NAME==TAIGA_xbar_2}]

# IP: bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_2 || ORIG_REF_NAME==TAIGA_axi_gpio_0_2}]

# IP: bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_3 || ORIG_REF_NAME==TAIGA_axi_gpio_0_3}]

# IP: bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_4 || ORIG_REF_NAME==TAIGA_axi_gpio_0_4}]

# IP: bd/TAIGA/ip/TAIGA_axi_timebase_wdt_0_0/TAIGA_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_timebase_wdt_0_0 || ORIG_REF_NAME==TAIGA_axi_timebase_wdt_0_0}]

# IP: bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_2/TAIGA_axi_fifo_mm_s_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_fifo_mm_s_0_2 || ORIG_REF_NAME==TAIGA_axi_fifo_mm_s_0_2}]

# IP: bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_uartlite_0_1 || ORIG_REF_NAME==TAIGA_axi_uartlite_0_1}]

# IP: bd/TAIGA/ip/TAIGA_auto_pc_0/TAIGA_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_auto_pc_0 || ORIG_REF_NAME==TAIGA_auto_pc_0}]

# XDC: bd/TAIGA/ip/TAIGA_processing_system7_0_0/TAIGA_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_processing_system7_0_0 || ORIG_REF_NAME==TAIGA_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_0 || ORIG_REF_NAME==TAIGA_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_0 || ORIG_REF_NAME==TAIGA_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_rst_production_controller_200M_0 || ORIG_REF_NAME==TAIGA_rst_production_controller_200M_0}]

# XDC: bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_rst_production_controller_200M_0 || ORIG_REF_NAME==TAIGA_rst_production_controller_200M_0}]

# XDC: bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_0/TAIGA_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_xbar_0/TAIGA_xbar_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_fifo_generator_0_0 || ORIG_REF_NAME==TAIGA_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_fifo_production_to_IOI_0 || ORIG_REF_NAME==TAIGA_fifo_production_to_IOI_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0_ooc.xdc

# XDC: ipshared/xilinx.com/fifo_multiplexer_v1_0/5a534b13/constraints/FIFO_multiplexer_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_microblaze_0_0 || ORIG_REF_NAME==TAIGA_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0_ooc_debug.xdc

# XDC: bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_dlmb_v10_0/TAIGA_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_dlmb_v10_0 || ORIG_REF_NAME==TAIGA_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_dlmb_v10_0/TAIGA_dlmb_v10_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_ilmb_v10_0/TAIGA_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_ilmb_v10_0 || ORIG_REF_NAME==TAIGA_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_ilmb_v10_0/TAIGA_ilmb_v10_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_dlmb_bram_if_cntlr_0/TAIGA_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_ilmb_bram_if_cntlr_0/TAIGA_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_lmb_bram_0/TAIGA_lmb_bram_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_backup_controller_axi_intc_0 || ORIG_REF_NAME==TAIGA_backup_controller_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_backup_controller_axi_intc_0 || ORIG_REF_NAME==TAIGA_backup_controller_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_mdm_1_0/TAIGA_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_mdm_1_0 || ORIG_REF_NAME==TAIGA_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_mdm_1_0/TAIGA_mdm_1_0_ooc_trace.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_timer_0_0/TAIGA_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_timer_0_0 || ORIG_REF_NAME==TAIGA_axi_timer_0_0}]

# XDC: bd/TAIGA/ip/TAIGA_axi_timer_0_0/TAIGA_axi_timer_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_xbar_1/TAIGA_xbar_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_1 || ORIG_REF_NAME==TAIGA_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_1 || ORIG_REF_NAME==TAIGA_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_1/TAIGA_axi_fifo_mm_s_0_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_fifo_IOI_to_production_0 || ORIG_REF_NAME==TAIGA_fifo_IOI_to_production_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_fifo_production_to_IOI_1 || ORIG_REF_NAME==TAIGA_fifo_production_to_IOI_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_microblaze_0_1 || ORIG_REF_NAME==TAIGA_microblaze_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1_ooc_debug.xdc

# XDC: bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_dlmb_v10_1/TAIGA_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_dlmb_v10_1 || ORIG_REF_NAME==TAIGA_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_dlmb_v10_1/TAIGA_dlmb_v10_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_ilmb_v10_1/TAIGA_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_ilmb_v10_1 || ORIG_REF_NAME==TAIGA_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_ilmb_v10_1/TAIGA_ilmb_v10_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_dlmb_bram_if_cntlr_1/TAIGA_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_ilmb_bram_if_cntlr_1/TAIGA_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_lmb_bram_1/TAIGA_lmb_bram_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_IO_intermediary_axi_intc_0 || ORIG_REF_NAME==TAIGA_IO_intermediary_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_IO_intermediary_axi_intc_0 || ORIG_REF_NAME==TAIGA_IO_intermediary_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_xbar_2/TAIGA_xbar_2_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_2 || ORIG_REF_NAME==TAIGA_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_2 || ORIG_REF_NAME==TAIGA_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_3 || ORIG_REF_NAME==TAIGA_axi_gpio_0_3}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_3 || ORIG_REF_NAME==TAIGA_axi_gpio_0_3}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_4 || ORIG_REF_NAME==TAIGA_axi_gpio_0_4}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_gpio_0_4 || ORIG_REF_NAME==TAIGA_axi_gpio_0_4}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_timebase_wdt_0_0/TAIGA_axi_timebase_wdt_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_axi_timebase_wdt_0_0 || ORIG_REF_NAME==TAIGA_axi_timebase_wdt_0_0}]

# XDC: bd/TAIGA/ip/TAIGA_axi_timebase_wdt_0_0/TAIGA_axi_timebase_wdt_0_0_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_2/TAIGA_axi_fifo_mm_s_0_2_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_uartlite_0_1 || ORIG_REF_NAME==TAIGA_axi_uartlite_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1_ooc.xdc

# XDC: bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_axi_uartlite_0_1 || ORIG_REF_NAME==TAIGA_axi_uartlite_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA/ip/TAIGA_auto_pc_0/TAIGA_auto_pc_0_ooc.xdc

# XDC: bd/TAIGA/TAIGA_ooc.xdc
