# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.cache/wt [current_project]
set_property parent.project_path /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/controls/TAIGA/HLS/FIFO_multiplexer/FIFO-multiplexer_solution/impl/ip [current_project]
add_files /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/TAIGA.bd
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_processing_system7_0_0/TAIGA_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_0/TAIGA_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_rst_production_controller_200M_0/TAIGA_rst_production_controller_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_0/TAIGA_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_xbar_0/TAIGA_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_generator_0_0/TAIGA_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_0/TAIGA_fifo_production_to_IOI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/ipshared/xilinx.com/fifo_multiplexer_v1_0/5a534b13/constraints/FIFO_multiplexer_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_microblaze_0_0/TAIGA_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_dlmb_v10_0/TAIGA_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_dlmb_v10_0/TAIGA_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_ilmb_v10_0/TAIGA_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_ilmb_v10_0/TAIGA_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_dlmb_bram_if_cntlr_0/TAIGA_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_ilmb_bram_if_cntlr_0/TAIGA_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_lmb_bram_0/TAIGA_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_backup_controller_axi_intc_0/TAIGA_backup_controller_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_mdm_1_0/TAIGA_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_mdm_1_0/TAIGA_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_timer_0_0/TAIGA_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_timer_0_0/TAIGA_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_xbar_1/TAIGA_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_1/TAIGA_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_1/TAIGA_axi_fifo_mm_s_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_IOI_to_production_0/TAIGA_fifo_IOI_to_production_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_fifo_production_to_IOI_1/TAIGA_fifo_production_to_IOI_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_microblaze_0_1/TAIGA_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_dlmb_v10_1/TAIGA_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_dlmb_v10_1/TAIGA_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_ilmb_v10_1/TAIGA_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_ilmb_v10_1/TAIGA_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_dlmb_bram_if_cntlr_1/TAIGA_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_ilmb_bram_if_cntlr_1/TAIGA_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_lmb_bram_1/TAIGA_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_IO_intermediary_axi_intc_0/TAIGA_IO_intermediary_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_quad_spi_0_0/TAIGA_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_xbar_2/TAIGA_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_2/TAIGA_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_3/TAIGA_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_gpio_0_4/TAIGA_axi_gpio_0_4.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_timebase_wdt_0_0/TAIGA_axi_timebase_wdt_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_timebase_wdt_0_0/TAIGA_axi_timebase_wdt_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_fifo_mm_s_0_2/TAIGA_axi_fifo_mm_s_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_axi_uartlite_0_1/TAIGA_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/ip/TAIGA_auto_pc_0/TAIGA_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/TAIGA_ooc.xdc]
set_property is_locked true [get_files /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/TAIGA.bd]

read_verilog -library xil_defaultlib /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/sources_1/bd/TAIGA/hdl/TAIGA_wrapper.v
read_xdc /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/constrs_1/new/TAIGA-RIP_Zybo.xdc
set_property used_in_implementation false [get_files /home/controls/TAIGA/Rotary-Inverted-Pendulum/Rotary-Inverted-Pendulum.srcs/constrs_1/new/TAIGA-RIP_Zybo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top TAIGA_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef TAIGA_wrapper.dcp
catch { report_utilization -file TAIGA_wrapper_utilization_synth.rpt -pb TAIGA_wrapper_utilization_synth.pb }
