webtalk_init -webtalk_dir /home/teja/Documents/TAIGA/Pendulum/Pendulum.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 31 18:41:27 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174141122_174141123_210588270_102" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4untqpb16hb21jp5of7o62ass5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1427840415000" -context "sdk\\\\bsp/1427840415000"
webtalk_add_data -client sdk -key hwid -value "1426643356000" -context "sdk\\\\bsp/1427840415000"
webtalk_add_data -client sdk -key os -value "freertos_zynq" -context "sdk\\\\bsp/1427840415000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1427840415000"
webtalk_add_data -client sdk -key uid -value "1427840484000" -context "sdk\\\\bsp/1427840484000"
webtalk_add_data -client sdk -key hwid -value "1426643356000" -context "sdk\\\\bsp/1427840484000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1427840484000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1427840484000"
webtalk_add_data -client sdk -key uid -value "1427840528000" -context "sdk\\\\bsp/1427840528000"
webtalk_add_data -client sdk -key hwid -value "1426643356000" -context "sdk\\\\bsp/1427840528000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1427840528000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1427840528000"
webtalk_transmit -clientid 488386297 -regid "174141122_174141123_210588270_102" -xml /home/teja/Documents/TAIGA/Pendulum/Pendulum.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/teja/Documents/TAIGA/Pendulum/Pendulum.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/teja/Documents/TAIGA/Pendulum/Pendulum.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
