#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 200000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 200000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 200000000

/******************************************************************/


/* Definitions for peripheral BACKUP_CONTROLLER */
#define XPAR_BACKUP_CONTROLLER_ADDR_TAG_BITS 0
#define XPAR_BACKUP_CONTROLLER_ALLOW_DCACHE_WR 1
#define XPAR_BACKUP_CONTROLLER_ALLOW_ICACHE_WR 1
#define XPAR_BACKUP_CONTROLLER_AREA_OPTIMIZED 0
#define XPAR_BACKUP_CONTROLLER_ASYNC_INTERRUPT 1
#define XPAR_BACKUP_CONTROLLER_AVOID_PRIMITIVES 0
#define XPAR_BACKUP_CONTROLLER_BASE_VECTORS 0x00000000
#define XPAR_BACKUP_CONTROLLER_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_BACKUP_CONTROLLER_CACHE_BYTE_SIZE 32768
#define XPAR_BACKUP_CONTROLLER_DATA_SIZE 32
#define XPAR_BACKUP_CONTROLLER_DCACHE_ADDR_TAG 0
#define XPAR_BACKUP_CONTROLLER_DCACHE_ALWAYS_USED 0
#define XPAR_BACKUP_CONTROLLER_DCACHE_BASEADDR 0x00000000
#define XPAR_BACKUP_CONTROLLER_DCACHE_BYTE_SIZE 32768
#define XPAR_BACKUP_CONTROLLER_DCACHE_DATA_WIDTH 0
#define XPAR_BACKUP_CONTROLLER_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_BACKUP_CONTROLLER_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_BACKUP_CONTROLLER_DCACHE_LINE_LEN 4
#define XPAR_BACKUP_CONTROLLER_DCACHE_USE_WRITEBACK 0
#define XPAR_BACKUP_CONTROLLER_DCACHE_VICTIMS 0
#define XPAR_BACKUP_CONTROLLER_DEBUG_COUNTER_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_DEBUG_ENABLED 1
#define XPAR_BACKUP_CONTROLLER_DEBUG_EVENT_COUNTERS 5
#define XPAR_BACKUP_CONTROLLER_DEBUG_EXTERNAL_TRACE 0
#define XPAR_BACKUP_CONTROLLER_DEBUG_LATENCY_COUNTERS 1
#define XPAR_BACKUP_CONTROLLER_DEBUG_PROFILE_SIZE 0
#define XPAR_BACKUP_CONTROLLER_DEBUG_TRACE_SIZE 8192
#define XPAR_BACKUP_CONTROLLER_DIV_ZERO_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_DYNAMIC_BUS_SIZING 0
#define XPAR_BACKUP_CONTROLLER_D_AXI 1
#define XPAR_BACKUP_CONTROLLER_D_LMB 1
#define XPAR_BACKUP_CONTROLLER_ECC_USE_CE_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_EDGE_IS_POSITIVE 1
#define XPAR_BACKUP_CONTROLLER_ENABLE_DISCRETE_PORTS 0
#define XPAR_BACKUP_CONTROLLER_ENDIANNESS 1
#define XPAR_BACKUP_CONTROLLER_FAULT_TOLERANT 0
#define XPAR_BACKUP_CONTROLLER_FPU_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_FREQ 200000000
#define XPAR_BACKUP_CONTROLLER_FSL_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_FSL_LINKS 0
#define XPAR_BACKUP_CONTROLLER_ICACHE_ALWAYS_USED 0
#define XPAR_BACKUP_CONTROLLER_ICACHE_BASEADDR 0x00000000
#define XPAR_BACKUP_CONTROLLER_ICACHE_DATA_WIDTH 0
#define XPAR_BACKUP_CONTROLLER_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_BACKUP_CONTROLLER_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_BACKUP_CONTROLLER_ICACHE_LINE_LEN 4
#define XPAR_BACKUP_CONTROLLER_ICACHE_STREAMS 0
#define XPAR_BACKUP_CONTROLLER_ICACHE_VICTIMS 0
#define XPAR_BACKUP_CONTROLLER_ILL_OPCODE_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_IMPRECISE_EXCEPTIONS 0
#define XPAR_BACKUP_CONTROLLER_INTERCONNECT 2
#define XPAR_BACKUP_CONTROLLER_INTERRUPT_IS_EDGE 0
#define XPAR_BACKUP_CONTROLLER_I_AXI 0
#define XPAR_BACKUP_CONTROLLER_I_LMB 1
#define XPAR_BACKUP_CONTROLLER_LOCKSTEP_SELECT 0
#define XPAR_BACKUP_CONTROLLER_LOCKSTEP_SLAVE 0
#define XPAR_BACKUP_CONTROLLER_M0_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M0_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M1_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M1_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M2_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M2_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M3_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M3_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M4_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M4_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M5_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M5_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M6_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M6_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M7_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M7_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M8_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M8_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M9_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M9_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M10_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M10_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M11_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M11_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M12_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M12_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M13_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M13_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M14_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M14_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_M15_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M15_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_MMU_DTLB_SIZE 4
#define XPAR_BACKUP_CONTROLLER_MMU_ITLB_SIZE 2
#define XPAR_BACKUP_CONTROLLER_MMU_PRIVILEGED_INSTR 0
#define XPAR_BACKUP_CONTROLLER_MMU_TLB_ACCESS 3
#define XPAR_BACKUP_CONTROLLER_MMU_ZONES 16
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_USER_SIGNALS 0
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_USER_VALUE 31
#define XPAR_BACKUP_CONTROLLER_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_DP_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_BACKUP_CONTROLLER_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_USER_SIGNALS 0
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_USER_VALUE 31
#define XPAR_BACKUP_CONTROLLER_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_IP_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_BACKUP_CONTROLLER_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_BACKUP_CONTROLLER_NUMBER_OF_PC_BRK 1
#define XPAR_BACKUP_CONTROLLER_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_BACKUP_CONTROLLER_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_BACKUP_CONTROLLER_NUM_SYNC_FF_CLK 2
#define XPAR_BACKUP_CONTROLLER_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_BACKUP_CONTROLLER_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_BACKUP_CONTROLLER_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_BACKUP_CONTROLLER_OPCODE_0X0_ILLEGAL 0
#define XPAR_BACKUP_CONTROLLER_OPTIMIZATION 0
#define XPAR_BACKUP_CONTROLLER_PC_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_PVR 0
#define XPAR_BACKUP_CONTROLLER_PVR_USER1 0x00
#define XPAR_BACKUP_CONTROLLER_PVR_USER2 0x00000000
#define XPAR_BACKUP_CONTROLLER_RESET_MSR 0x00000000
#define XPAR_BACKUP_CONTROLLER_S0_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S0_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S1_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S1_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S2_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S2_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S3_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S3_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S4_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S4_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S5_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S5_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S6_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S6_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S7_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S7_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S8_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S8_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S9_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S9_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S10_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S10_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S11_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S11_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S12_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S12_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S13_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S13_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S14_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S14_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_S15_AXIS_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_S15_AXIS_PROTOCOL GENERIC
#define XPAR_BACKUP_CONTROLLER_SCO 0
#define XPAR_BACKUP_CONTROLLER_TRACE 0
#define XPAR_BACKUP_CONTROLLER_UNALIGNED_EXCEPTIONS 0
#define XPAR_BACKUP_CONTROLLER_USE_BARREL 1
#define XPAR_BACKUP_CONTROLLER_USE_BRANCH_TARGET_CACHE 0
#define XPAR_BACKUP_CONTROLLER_USE_CONFIG_RESET 0
#define XPAR_BACKUP_CONTROLLER_USE_DCACHE 0
#define XPAR_BACKUP_CONTROLLER_USE_DIV 1
#define XPAR_BACKUP_CONTROLLER_USE_EXTENDED_FSL_INSTR 0
#define XPAR_BACKUP_CONTROLLER_USE_EXT_BRK 0
#define XPAR_BACKUP_CONTROLLER_USE_EXT_NM_BRK 0
#define XPAR_BACKUP_CONTROLLER_USE_FPU 2
#define XPAR_BACKUP_CONTROLLER_USE_HW_MUL 1
#define XPAR_BACKUP_CONTROLLER_USE_ICACHE 0
#define XPAR_BACKUP_CONTROLLER_USE_INTERRUPT 2
#define XPAR_BACKUP_CONTROLLER_USE_MMU 0
#define XPAR_BACKUP_CONTROLLER_USE_MSR_INSTR 1
#define XPAR_BACKUP_CONTROLLER_USE_PCMP_INSTR 1
#define XPAR_BACKUP_CONTROLLER_USE_REORDER_INSTR 1
#define XPAR_BACKUP_CONTROLLER_USE_STACK_PROTECTION 0
#define XPAR_BACKUP_CONTROLLER_COMPONENT_NAME TAIGA_System_microblaze_0_1
#define XPAR_BACKUP_CONTROLLER_EDK_IPTYPE PROCESSOR
#define XPAR_BACKUP_CONTROLLER_EDK_SPECIAL microblaze
#define XPAR_BACKUP_CONTROLLER_G_TEMPLATE_LIST 0
#define XPAR_BACKUP_CONTROLLER_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 1
#define XPAR_MICROBLAZE_ID 1
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 0
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x00000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 0
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 200000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 1
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 2
#define XPAR_MICROBLAZE_USE_HW_MUL 1
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME TAIGA_System_microblaze_0_1
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 2

/* Definitions for peripheral BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x00007FFF
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 1
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x00007FFF
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/******************************************************************/

/* Canonical definitions for peripheral BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_0_WRITE_ACCESS 2
#define XPAR_BRAM_0_BASEADDR 0x00000000
#define XPAR_BRAM_0_HIGHADDR 0x00007FFF

/* Canonical definitions for peripheral BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_BACKUP_CONTROLLER_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32
#define XPAR_BRAM_1_ECC 0
#define XPAR_BRAM_1_FAULT_INJECT 0
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_1_WRITE_ACCESS 2
#define XPAR_BRAM_1_BASEADDR 0x00000000
#define XPAR_BRAM_1_HIGHADDR 0x00007FFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_BACKUP_CONTROLLER_OUT */
#define XPAR_AXI_GPIO_BACKUP_CONTROLLER_OUT_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_BACKUP_CONTROLLER_OUT_HIGHADDR 0x4000FFFF
#define XPAR_AXI_GPIO_BACKUP_CONTROLLER_OUT_DEVICE_ID 0
#define XPAR_AXI_GPIO_BACKUP_CONTROLLER_OUT_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_BACKUP_CONTROLLER_OUT_IS_DUAL 1


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO_BACKUP_CONTROLLER_OUT */
#define XPAR_GPIO_0_BASEADDR 0x40000000
#define XPAR_GPIO_0_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_BACKUP_CONTROLLER_OUT_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 1
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral BACKUP_CONTROLLER_AXI_INTC */
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_DEVICE_ID 0
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_BASEADDR 0x41200000
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_HIGHADDR 0x4120FFFF
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_KIND_OF_INTR 0xFFFFFFFE
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_HAS_FAST 1
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_IVAR_RESET_VALUE 0x00000010
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_NUM_INTR_INPUTS 1


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_BACKUP_CONTROLLER_AXI_INTC_DEVICE_ID
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_TYPE 0
#define XPAR_AXI_TIMER_BACKUP_CONTROLLER_INTERRUPT_MASK 0X000001
#define XPAR_BACKUP_CONTROLLER_AXI_INTC_AXI_TIMER_BACKUP_CONTROLLER_INTERRUPT_INTR 0

/******************************************************************/

/* Canonical definitions for peripheral BACKUP_CONTROLLER_AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_BACKUP_CONTROLLER_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000
#define XPAR_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFE
#define XPAR_INTC_0_HAS_FAST 1
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x00000010
#define XPAR_INTC_0_NUM_INTR_INPUTS 1
#define XPAR_INTC_0_INTC_TYPE 0

#define XPAR_INTC_0_TMRCTR_0_VEC_ID XPAR_BACKUP_CONTROLLER_AXI_INTC_AXI_TIMER_BACKUP_CONTROLLER_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver LLFIFO */
#define XPAR_XLLFIFO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_FIFO_BACKUP */
#define XPAR_AXI_FIFO_BACKUP_DEVICE_ID 0
#define XPAR_AXI_FIFO_BACKUP_BASEADDR 0x44A00000
#define XPAR_AXI_FIFO_BACKUP_HIGHADDR 0x44A0FFFF
#define XPAR_AXI_FIFO_BACKUP_AXI4_BASEADDR 0x80001000
#define XPAR_AXI_FIFO_BACKUP_AXI4_HIGHADDR 0x80002FFF
#define XPAR_AXI_FIFO_BACKUP_DATA_INTERFACE_TYPE 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_FIFO_BACKUP */
#define XPAR_AXI_FIFO_0_DEVICE_ID XPAR_AXI_FIFO_BACKUP_DEVICE_ID
#define XPAR_AXI_FIFO_0_BASEADDR 0x44A00000
#define XPAR_AXI_FIFO_0_HIGHADDR 0x44A0FFFF
#define XPAR_AXI_FIFO_0_AXI4_BASEADDR 0x80001000
#define XPAR_AXI_FIFO_0_AXI4_HIGHADDR 0x80002FFF
#define XPAR_AXI_FIFO_0_DATA_INTERFACE_TYPE 0


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_BACKUP_CONTROLLER */
#define XPAR_AXI_TIMER_BACKUP_CONTROLLER_DEVICE_ID 0
#define XPAR_AXI_TIMER_BACKUP_CONTROLLER_BASEADDR 0x41C00000
#define XPAR_AXI_TIMER_BACKUP_CONTROLLER_HIGHADDR 0x41C0FFFF
#define XPAR_AXI_TIMER_BACKUP_CONTROLLER_CLOCK_FREQ_HZ 200000000


/******************************************************************/

/* Canonical definitions for peripheral AXI_TIMER_BACKUP_CONTROLLER */
#define XPAR_TMRCTR_0_DEVICE_ID 0
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000
#define XPAR_TMRCTR_0_HIGHADDR 0x41C0FFFF
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_AXI_TIMER_BACKUP_CONTROLLER_CLOCK_FREQ_HZ

/******************************************************************/

#endif  /* end of protection macro */
