// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "fifo_dequeue.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fifo_dequeue::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fifo_dequeue::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> fifo_dequeue::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> fifo_dequeue::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> fifo_dequeue::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> fifo_dequeue::ap_const_lv1_1 = "1";
const sc_lv<1> fifo_dequeue::ap_const_lv1_0 = "0";
const sc_lv<32> fifo_dequeue::ap_const_lv32_1 = "1";

fifo_dequeue::fifo_dequeue(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( fifo_recv_valid_read_read_fu_48_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( fifo_recv_valid_read_read_fu_48_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( fifo_data );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( fifo_recv_valid_read_read_fu_48_p2 );

    SC_METHOD(thread_ap_sig_bdd_18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_18 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_39 );

    SC_METHOD(thread_fifo_recv_enable);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( fifo_recv_enable_preg );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( fifo_recv_valid_read_read_fu_48_p2 );

    SC_METHOD(thread_fifo_recv_valid_read_read_fu_48_p2);
    sensitive << ( fifo_recv_valid );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( fifo_recv_valid_read_read_fu_48_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    fifo_recv_enable_preg = "0";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fifo_dequeue_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, fifo_data, "(port)fifo_data");
    sc_trace(mVcdFile, fifo_recv_enable, "(port)fifo_recv_enable");
    sc_trace(mVcdFile, fifo_recv_valid, "(port)fifo_recv_valid");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_18, "ap_sig_bdd_18");
    sc_trace(mVcdFile, fifo_recv_enable_preg, "fifo_recv_enable_preg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_39, "ap_sig_bdd_39");
    sc_trace(mVcdFile, fifo_recv_valid_read_read_fu_48_p2, "fifo_recv_valid_read_read_fu_48_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("fifo_dequeue.hdltvin.dat");
    mHdltvoutHandle.open("fifo_dequeue.hdltvout.dat");
}

fifo_dequeue::~fifo_dequeue() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void fifo_dequeue::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        fifo_recv_enable_preg = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            fifo_recv_enable_preg = ap_const_lv1_1;
        }
    }
}

void fifo_dequeue::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, fifo_recv_valid_read_read_fu_48_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fifo_dequeue::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fifo_dequeue::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, fifo_recv_valid_read_read_fu_48_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fifo_dequeue::thread_ap_return() {
    ap_return = fifo_data.read();
}

void fifo_dequeue::thread_ap_sig_bdd_18() {
    ap_sig_bdd_18 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void fifo_dequeue::thread_ap_sig_bdd_39() {
    ap_sig_bdd_39 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void fifo_dequeue::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_18.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void fifo_dequeue::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_39.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void fifo_dequeue::thread_fifo_recv_enable() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, fifo_recv_valid_read_read_fu_48_p2.read()))) {
        fifo_recv_enable = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        fifo_recv_enable = ap_const_lv1_1;
    } else {
        fifo_recv_enable = fifo_recv_enable_preg.read();
    }
}

void fifo_dequeue::thread_fifo_recv_valid_read_read_fu_48_p2() {
    fifo_recv_valid_read_read_fu_48_p2 = fifo_recv_valid.read();
}

void fifo_dequeue::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, fifo_recv_valid_read_read_fu_48_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void fifo_dequeue::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"fifo_data\" :  \"" << fifo_data.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fifo_recv_enable\" :  \"" << fifo_recv_enable.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"fifo_recv_valid\" :  \"" << fifo_recv_valid.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

