# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TAIGA_Pendulum_ZYBO.xdc

# Block Designs: bd/TAIGA_System/TAIGA_System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System || ORIG_REF_NAME==TAIGA_System}]

# IP: bd/TAIGA_System/ip/TAIGA_System_processing_system7_0_0/TAIGA_System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_processing_system7_0_0 || ORIG_REF_NAME==TAIGA_System_processing_system7_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_microblaze_0_0/TAIGA_System_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_microblaze_0_0 || ORIG_REF_NAME==TAIGA_System_microblaze_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_dlmb_v10_1/TAIGA_System_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_dlmb_v10_1 || ORIG_REF_NAME==TAIGA_System_dlmb_v10_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_ilmb_v10_1/TAIGA_System_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_ilmb_v10_1 || ORIG_REF_NAME==TAIGA_System_ilmb_v10_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_dlmb_bram_if_cntlr_1/TAIGA_System_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==TAIGA_System_dlmb_bram_if_cntlr_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_ilmb_bram_if_cntlr_1/TAIGA_System_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==TAIGA_System_ilmb_bram_if_cntlr_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_lmb_bram_1/TAIGA_System_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_lmb_bram_1 || ORIG_REF_NAME==TAIGA_System_lmb_bram_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_IO_Intermediary_axi_periph_0/TAIGA_System_IO_Intermediary_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_IO_Intermediary_axi_periph_0 || ORIG_REF_NAME==TAIGA_System_IO_Intermediary_axi_periph_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_IO_Intermediary_axi_intc_0/TAIGA_System_IO_Intermediary_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_IO_Intermediary_axi_intc_0 || ORIG_REF_NAME==TAIGA_System_IO_Intermediary_axi_intc_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_IO_Intermediary_xlconcat_0/TAIGA_System_IO_Intermediary_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_IO_Intermediary_xlconcat_0 || ORIG_REF_NAME==TAIGA_System_IO_Intermediary_xlconcat_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_mdm_1_1/TAIGA_System_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_mdm_1_1 || ORIG_REF_NAME==TAIGA_System_mdm_1_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_rst_production_controller_100M_1/TAIGA_System_rst_production_controller_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_rst_production_controller_100M_1 || ORIG_REF_NAME==TAIGA_System_rst_production_controller_100M_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_quad_spi_0_0/TAIGA_System_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_System_axi_quad_spi_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_xbar_0/TAIGA_System_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_xbar_0 || ORIG_REF_NAME==TAIGA_System_xbar_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_0/TAIGA_System_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_0 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_1/TAIGA_System_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_1 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_timebase_wdt_0_0/TAIGA_System_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_timebase_wdt_0_0 || ORIG_REF_NAME==TAIGA_System_axi_timebase_wdt_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_fifo_generator_0_0/TAIGA_System_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_generator_0_0 || ORIG_REF_NAME==TAIGA_System_fifo_generator_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_fifo_production_to_IOI_0/TAIGA_System_fifo_production_to_IOI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_production_to_IOI_0 || ORIG_REF_NAME==TAIGA_System_fifo_production_to_IOI_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_fifo_IOI_to_production_0/TAIGA_System_fifo_IOI_to_production_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_IOI_to_production_0 || ORIG_REF_NAME==TAIGA_System_fifo_IOI_to_production_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_fifo_production_to_IOI_1/TAIGA_System_fifo_production_to_IOI_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_production_to_IOI_1 || ORIG_REF_NAME==TAIGA_System_fifo_production_to_IOI_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_mm_s_0_0/TAIGA_System_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==TAIGA_System_axi_fifo_mm_s_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_IOI_dequeue_0/TAIGA_System_axi_fifo_IOI_dequeue_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_fifo_IOI_dequeue_0 || ORIG_REF_NAME==TAIGA_System_axi_fifo_IOI_dequeue_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_IOI_dequeue_1/TAIGA_System_axi_fifo_IOI_dequeue_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_fifo_IOI_dequeue_1 || ORIG_REF_NAME==TAIGA_System_axi_fifo_IOI_dequeue_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_IOI_dequeue_2/TAIGA_System_axi_fifo_IOI_dequeue_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_fifo_IOI_dequeue_2 || ORIG_REF_NAME==TAIGA_System_axi_fifo_IOI_dequeue_2}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_backup_dequeue_0/TAIGA_System_axi_fifo_backup_dequeue_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_fifo_backup_dequeue_0 || ORIG_REF_NAME==TAIGA_System_axi_fifo_backup_dequeue_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_production_dequeue_0/TAIGA_System_axi_fifo_production_dequeue_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_fifo_production_dequeue_0 || ORIG_REF_NAME==TAIGA_System_axi_fifo_production_dequeue_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_queue_multiplexer_0_0/TAIGA_System_queue_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_queue_multiplexer_0_0 || ORIG_REF_NAME==TAIGA_System_queue_multiplexer_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_microblaze_0_1/TAIGA_System_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_microblaze_0_1 || ORIG_REF_NAME==TAIGA_System_microblaze_0_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_dlmb_v10_0/TAIGA_System_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_dlmb_v10_0 || ORIG_REF_NAME==TAIGA_System_dlmb_v10_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_ilmb_v10_0/TAIGA_System_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_ilmb_v10_0 || ORIG_REF_NAME==TAIGA_System_ilmb_v10_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_dlmb_bram_if_cntlr_0/TAIGA_System_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TAIGA_System_dlmb_bram_if_cntlr_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_ilmb_bram_if_cntlr_0/TAIGA_System_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TAIGA_System_ilmb_bram_if_cntlr_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_lmb_bram_0/TAIGA_System_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_lmb_bram_0 || ORIG_REF_NAME==TAIGA_System_lmb_bram_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_backup_controller_axi_periph_0/TAIGA_System_backup_controller_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_backup_controller_axi_periph_0 || ORIG_REF_NAME==TAIGA_System_backup_controller_axi_periph_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_backup_controller_axi_intc_0/TAIGA_System_backup_controller_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_backup_controller_axi_intc_0 || ORIG_REF_NAME==TAIGA_System_backup_controller_axi_intc_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_timer_0_0/TAIGA_System_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_timer_0_0 || ORIG_REF_NAME==TAIGA_System_axi_timer_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_xbar_1/TAIGA_System_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_xbar_1 || ORIG_REF_NAME==TAIGA_System_xbar_1}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_2/TAIGA_System_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_2 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_2}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_interconnect_0_0/TAIGA_System_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_interconnect_0_0 || ORIG_REF_NAME==TAIGA_System_axi_interconnect_0_0}]

# IP: bd/TAIGA_System/ip/TAIGA_System_xbar_2/TAIGA_System_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_xbar_2 || ORIG_REF_NAME==TAIGA_System_xbar_2}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_3/TAIGA_System_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_3 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_3}]

# IP: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_4/TAIGA_System_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_4 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_4}]

# IP: bd/TAIGA_System/ip/TAIGA_System_auto_pc_0/TAIGA_System_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_auto_pc_0 || ORIG_REF_NAME==TAIGA_System_auto_pc_0}]

# XDC: bd/TAIGA_System/ip/TAIGA_System_processing_system7_0_0/TAIGA_System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_processing_system7_0_0 || ORIG_REF_NAME==TAIGA_System_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_microblaze_0_0/TAIGA_System_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_microblaze_0_0 || ORIG_REF_NAME==TAIGA_System_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_microblaze_0_0/TAIGA_System_microblaze_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_dlmb_v10_1/TAIGA_System_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_dlmb_v10_1 || ORIG_REF_NAME==TAIGA_System_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_dlmb_v10_1/TAIGA_System_dlmb_v10_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_ilmb_v10_1/TAIGA_System_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_ilmb_v10_1 || ORIG_REF_NAME==TAIGA_System_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_ilmb_v10_1/TAIGA_System_ilmb_v10_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_dlmb_bram_if_cntlr_1/TAIGA_System_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_ilmb_bram_if_cntlr_1/TAIGA_System_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_lmb_bram_1/TAIGA_System_lmb_bram_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_IO_Intermediary_axi_intc_0/TAIGA_System_IO_Intermediary_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_IO_Intermediary_axi_intc_0 || ORIG_REF_NAME==TAIGA_System_IO_Intermediary_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_IO_Intermediary_axi_intc_0/TAIGA_System_IO_Intermediary_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_IO_Intermediary_axi_intc_0 || ORIG_REF_NAME==TAIGA_System_IO_Intermediary_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_IO_Intermediary_axi_intc_0/TAIGA_System_IO_Intermediary_axi_intc_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_mdm_1_1/TAIGA_System_mdm_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_mdm_1_1 || ORIG_REF_NAME==TAIGA_System_mdm_1_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_mdm_1_1/TAIGA_System_mdm_1_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_rst_production_controller_100M_1/TAIGA_System_rst_production_controller_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_rst_production_controller_100M_1 || ORIG_REF_NAME==TAIGA_System_rst_production_controller_100M_1}]

# XDC: bd/TAIGA_System/ip/TAIGA_System_rst_production_controller_100M_1/TAIGA_System_rst_production_controller_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_rst_production_controller_100M_1 || ORIG_REF_NAME==TAIGA_System_rst_production_controller_100M_1}]

# XDC: bd/TAIGA_System/ip/TAIGA_System_rst_production_controller_100M_1/TAIGA_System_rst_production_controller_100M_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_quad_spi_0_0/TAIGA_System_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_System_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_quad_spi_0_0/TAIGA_System_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_System_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_quad_spi_0_0/TAIGA_System_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_quad_spi_0_0/TAIGA_System_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_quad_spi_0_0 || ORIG_REF_NAME==TAIGA_System_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_xbar_0/TAIGA_System_xbar_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_0/TAIGA_System_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_0 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_0/TAIGA_System_axi_gpio_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_0/TAIGA_System_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_0 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_1/TAIGA_System_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_1 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_1/TAIGA_System_axi_gpio_0_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_1/TAIGA_System_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_1 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_timebase_wdt_0_0/TAIGA_System_axi_timebase_wdt_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_timebase_wdt_0_0 || ORIG_REF_NAME==TAIGA_System_axi_timebase_wdt_0_0}]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_timebase_wdt_0_0/TAIGA_System_axi_timebase_wdt_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_generator_0_0/TAIGA_System_fifo_generator_0_0/TAIGA_System_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_generator_0_0 || ORIG_REF_NAME==TAIGA_System_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_generator_0_0/TAIGA_System_fifo_generator_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_production_to_IOI_0/TAIGA_System_fifo_production_to_IOI_0/TAIGA_System_fifo_production_to_IOI_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_production_to_IOI_0 || ORIG_REF_NAME==TAIGA_System_fifo_production_to_IOI_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_production_to_IOI_0/TAIGA_System_fifo_production_to_IOI_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_IOI_to_production_0/TAIGA_System_fifo_IOI_to_production_0/TAIGA_System_fifo_IOI_to_production_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_IOI_to_production_0 || ORIG_REF_NAME==TAIGA_System_fifo_IOI_to_production_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_IOI_to_production_0/TAIGA_System_fifo_IOI_to_production_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_production_to_IOI_1/TAIGA_System_fifo_production_to_IOI_1/TAIGA_System_fifo_production_to_IOI_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_fifo_production_to_IOI_1 || ORIG_REF_NAME==TAIGA_System_fifo_production_to_IOI_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_fifo_production_to_IOI_1/TAIGA_System_fifo_production_to_IOI_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_mm_s_0_0/TAIGA_System_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_IOI_dequeue_0/TAIGA_System_axi_fifo_IOI_dequeue_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_IOI_dequeue_1/TAIGA_System_axi_fifo_IOI_dequeue_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_IOI_dequeue_2/TAIGA_System_axi_fifo_IOI_dequeue_2_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_backup_dequeue_0/TAIGA_System_axi_fifo_backup_dequeue_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_fifo_production_dequeue_0/TAIGA_System_axi_fifo_production_dequeue_0_ooc.xdc

# XDC: ipshared/xilinx.com/queue_multiplexer_v1_0/89731f10/constraints/queue_multiplexer_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_microblaze_0_1/TAIGA_System_microblaze_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_microblaze_0_1 || ORIG_REF_NAME==TAIGA_System_microblaze_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_microblaze_0_1/TAIGA_System_microblaze_0_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_dlmb_v10_0/TAIGA_System_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_dlmb_v10_0 || ORIG_REF_NAME==TAIGA_System_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_dlmb_v10_0/TAIGA_System_dlmb_v10_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_ilmb_v10_0/TAIGA_System_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_ilmb_v10_0 || ORIG_REF_NAME==TAIGA_System_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_ilmb_v10_0/TAIGA_System_ilmb_v10_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_dlmb_bram_if_cntlr_0/TAIGA_System_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_ilmb_bram_if_cntlr_0/TAIGA_System_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_lmb_bram_0/TAIGA_System_lmb_bram_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_backup_controller_axi_intc_0/TAIGA_System_backup_controller_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_backup_controller_axi_intc_0 || ORIG_REF_NAME==TAIGA_System_backup_controller_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_backup_controller_axi_intc_0/TAIGA_System_backup_controller_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_backup_controller_axi_intc_0 || ORIG_REF_NAME==TAIGA_System_backup_controller_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_backup_controller_axi_intc_0/TAIGA_System_backup_controller_axi_intc_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_timer_0_0/TAIGA_System_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_timer_0_0 || ORIG_REF_NAME==TAIGA_System_axi_timer_0_0}]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_timer_0_0/TAIGA_System_axi_timer_0_0_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_xbar_1/TAIGA_System_xbar_1_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_2/TAIGA_System_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_2 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_2/TAIGA_System_axi_gpio_0_2_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_2/TAIGA_System_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_2 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_xbar_2/TAIGA_System_xbar_2_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_3/TAIGA_System_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_3 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_3}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_3/TAIGA_System_axi_gpio_0_3_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_3/TAIGA_System_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_3 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_3}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_4/TAIGA_System_axi_gpio_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_4 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_4}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_4/TAIGA_System_axi_gpio_0_4_ooc.xdc

# XDC: bd/TAIGA_System/ip/TAIGA_System_axi_gpio_0_4/TAIGA_System_axi_gpio_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TAIGA_System_axi_gpio_0_4 || ORIG_REF_NAME==TAIGA_System_axi_gpio_0_4}] {/U0 }]/U0 ]]

# XDC: bd/TAIGA_System/ip/TAIGA_System_auto_pc_0/TAIGA_System_auto_pc_0_ooc.xdc

# XDC: bd/TAIGA_System/TAIGA_System_ooc.xdc
