// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _queue_multiplexer_HH_
#define _queue_multiplexer_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct queue_multiplexer : public sc_module {
    // Port declarations 19
    sc_in< sc_logic > switch_select;
    sc_in< sc_lv<32> > rx_data_a;
    sc_out< sc_logic > rx_ready_a;
    sc_in< sc_logic > rx_valid_a;
    sc_in< sc_lv<32> > rx_data_b;
    sc_out< sc_logic > rx_ready_b;
    sc_in< sc_logic > rx_valid_b;
    sc_out< sc_lv<32> > rx_data;
    sc_in< sc_logic > rx_ready;
    sc_out< sc_logic > rx_valid;
    sc_out< sc_lv<32> > tx_data_a;
    sc_in< sc_logic > tx_ready_a;
    sc_out< sc_logic > tx_valid_a;
    sc_out< sc_lv<32> > tx_data_b;
    sc_in< sc_logic > tx_ready_b;
    sc_out< sc_logic > tx_valid_b;
    sc_in< sc_lv<32> > tx_data;
    sc_out< sc_logic > tx_ready;
    sc_in< sc_logic > tx_valid;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    queue_multiplexer(sc_module_name name);
    SC_HAS_PROCESS(queue_multiplexer);

    ~queue_multiplexer();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > switch_select_read_read_fu_62_p2;
    static const bool ap_true;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_rx_data();
    void thread_rx_ready_a();
    void thread_rx_ready_b();
    void thread_rx_valid();
    void thread_switch_select_read_read_fu_62_p2();
    void thread_tx_data_a();
    void thread_tx_data_b();
    void thread_tx_ready();
    void thread_tx_valid_a();
    void thread_tx_valid_b();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
